include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
#include /usr/share/cibs/rules/autoreconf.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk

summary := Generic library support script
license := GPL
license-file := COPYING

build-depends += \

# build-conflicts +=

home     := http://www.gnu.org/software/libtool/
name     := libtool
version  := 2.2.2
archive  := $(name)-$(version).tar.gz
download := http://ftp.gnu.org/gnu/$(name)/$(archive)
checksum := \
     md5:9281a5f1976da110be872b1ba048d8ac \
    sha1:41e0d829188083ab9f6bedf2b9eca89543dc0f8a \
  sha256:c3963d969e13588fb142001d5a81c07962dc2ce7c03e2f4f551a29760e844a10 \
    size:2223210
