include /usr/share/cibs/rules/ips.mk
include /usr/share/cibs/rules/archive.mk
#include /usr/share/cibs/rules/patch.mk
#include /usr/share/cibs/rules/autoreconf.mk
include /usr/share/cibs/rules/autotools.mk
include /usr/share/cibs/rules/32.mk
include /usr/share/cibs/rules/64.mk


summary := 
license := 
license-file := 

build-depends +=

configure-env +=

configure-options +=

home     :=
name     :=
version  :=
archive  :=
download :=

