#!/bin/sh

set -e
set -u

fatal () {
    echo "$@" >&2
    exit 1
}

archive="$1"
url="$2"
shift 2

wget=`type -p wget || true`
curl=`type -p curl || true`

if [ -n "$wget" ]; then
    $wget -O "$archive" "$url" || ( rm -f "$archive"; fatal "download failed" )
elif [ -n "$curl" ]; then
    $curl -L -v "$url" > "$archive" || ( rm -f "$archive"; fatal "download failed" )
else
    fatal "Don't know how to download"
fi

